- name: Deploy over SSH (public repo)
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.DEPLOY_HOST }}       # 36.95.208.100
    port: 223
    username: ${{ secrets.DEPLOY_USER }}   # deploy
    key_path: ~/.ssh/deploy_key            # <-- file key yang sudah kamu tulis di step sebelumnya
    script_stop: true
    command_timeout: 15m
    script: |
      bash -lc '
        set -euxo pipefail

        APP_DIR=/var/www/laravel
        REPO_URL=https://github.com/khoirurrozikin86/dangerous.git
        BRANCH=main

        mkdir -p "$APP_DIR"
        if [ ! -d "$APP_DIR/.git" ]; then
          git clone "$REPO_URL" "$APP_DIR"
        fi

        cd "$APP_DIR"
        git config --global --add safe.directory "$APP_DIR"
        git fetch origin "$BRANCH" --prune
        git reset --hard "origin/$BRANCH"

        # composer user-level
        if ! command -v composer >/dev/null 2>&1; then
          curl -sS https://getcomposer.org/installer | php
          mkdir -p "$HOME/.local/bin"
          mv composer.phar "$HOME/.local/bin/composer"
          chmod +x "$HOME/.local/bin/composer"
          export PATH="$HOME/.local/bin:$PATH"
        fi

        composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

        [ -f .env ] || cp .env.example .env || true
        php artisan key:generate || true
        php artisan migrate --force || true

        php artisan config:clear || true
        php artisan config:cache || true
        php artisan route:cache || true
        php artisan view:cache || true

        echo "✅ Deploy selesai $(date)"
      '
